Update creationflags in list value of _Popen_defaults.
It looks like this code might have been originally written to use a
dict, and the mswindows branch didn't get updated to work with a list of
tuples instead. This is the exception I was getting on Windows:

Traceback (most recent call last):
  File "obfs-flash-client", line 11, in <module>
    from pyptlib.util.subproc import auto_killall, Popen
  File "pyptlib\util\subproc.py", line 31, in <module>
    _Popen_defaults['creationflags'] |= subprocess.CREATE_NEW_PROCESS_GROUP
TypeError: list indices must be integers, not str